make Www-Authentication header parsing case-insensitive
camallo/dkregistry-rs pull request #211
Opened 2021-11-29 16:03 UTC by ChristianLoewel

Closes #210 

I made the following changes to make the header parsing case-insensitive:

- adapted the Regex to match method and key case-insensitively. This also required some changes in the positioning of whitespace character classes (\s) to not break the group matching.
- convert the matched method to lowercase
- rename lowercase method to PascalCase when deserializing using serde annotation
- convert all matched keys to lowercase

I also extended the relevant tests to include some variations in upper/lowercase methods and keys.

2021-12-01 13:34 UTC, vrutkovs commented
LGTM, @lucab would you like to take another look?

2021-12-01 14:24 UTC, lucab commented
LGTM, though I'm not actively maintaining nor consuming this repository anymore.

2021-12-01 17:29 UTC, vrutkovs commented
Sorry, have to close & reopen again, as Travis was replaced with Github Actions

2021-12-01 17:46 UTC, vrutkovs commented
LGTM, however `bearer_realm_parses_correctly` needs a slight update

2021-12-01 18:00 UTC, vrutkovs commented on src/v2/auth.rs
> +        ] {
```suggestion
].iter() {
```
To support Rust 1.46

2021-12-01 18:01 UTC, vrutkovs commented on src/v2/auth.rs
> +            let content = WwwAuthenticateHeaderContent::from_www_authentication_header(header_value)?;
```suggestion
            let content = WwwAuthenticateHeaderContent::from_www_authentication_header(header_value.to_owned())?;
```
for Rust 1.46 support

2021-12-01 18:01 UTC, vrutkovs commented on src/v2/auth.rs
> +        ] {
Same here - `.iter()` and `.to_owned()` later

2021-12-02 07:55 UTC, ChristianLoewel commented
Thanks, @vrutkovs! I updated the PR accordingly.

2021-12-02 11:04 UTC, vrutkovs commented on src/v2/auth.rs
> +                        capture.name("key").map(|n| n.as_str().to_lowercase().to_string()),
```suggestion
                        capture
                            .name("key")
                            .map(|n| n.as_str().to_lowercase().to_string()),
```
See `cargo fmt` from lints check

2021-12-02 11:36 UTC, vrutkovs requested changes

2021-12-02 11:36 UTC, vrutkovs commented on src/v2/auth.rs
>              .to_string();
No longer needed:
```
 Error:    --> src/v2/auth.rs:138:13
    |
138 |             .to_string();
    |             ^^^^^^^^^^^^ help: remove this
    |
    = note: `-D clippy::redundant-clone` implied by `-D warnings`
```

2021-12-02 11:36 UTC, vrutkovs commented on src/v2/auth.rs
> +                            .map(|n| n.as_str().to_lowercase().to_string()),
```suggestion
                            .map(|n| n.as_str().to_lowercase()),
```
`to_lowercase` returns String

2021-12-02 11:53 UTC, ChristianLoewel commented
yet another formatting change. Sorry for this back and forth, but now it should be okay.

2021-12-02 11:55 UTC, vrutkovs commented
Looks great now, thanks!

2021-12-02 11:56 UTC, merged